# Generated by Django 5.2.17 on 2026-09-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='card',
            name='domain_token',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='card',
            name='domain_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
