# Generated by Django 5.2.17 on 2026-09-25 20:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('workplace', models.CharField(choices=[('onsite', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='onsite', max_length=8)),
                ('kind', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('contract', 'Contract')], default='full_time', max_length=12)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='PKR', max_length=6)),
                ('salary_period', models.CharField(choices=[('month', 'a month'), ('year', 'a year'), ('hour', 'an hour'), ('project', 'for the project')], default='month', max_length=8)),
                ('show_salary', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=6000)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('deadline', models.DateField()),
                ('closed', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(db_index=True, default=False, help_text='Hidden by a moderator')),
                ('applicants_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='JobReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fee', 'Asks for money or a fee'), ('scam', 'Scam or fake job'), ('wrong', 'Wrong or misleading'), ('abuse', 'Offensive'), ('other', 'Something else')], max_length=8)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('handled', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.job')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Not selected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('job', 'applicant')},
            },
        ),
    ]
