# Generated by Django 5.2.17 on 2026-10-10 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('kind', models.CharField(default='b2c', max_length=4)),
                ('city', models.CharField(max_length=60)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('about', models.TextField(blank=True, default='', max_length=2000)),
                ('logo', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(db_index=True, default='pending', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('rating_sum', models.PositiveIntegerField(default=0)),
                ('rating_n', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list)),
                ('subtotal', models.PositiveIntegerField()),
                ('delivery', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField()),
                ('fee', models.PositiveIntegerField(default=0)),
                ('payment', models.CharField(default='cod', max_length=6)),
                ('group', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('status', models.CharField(db_index=True, default='placed', max_length=12)),
                ('name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=60)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('courier', models.CharField(blank=True, default='', max_length=40)),
                ('tracking', models.CharField(blank=True, default='', max_length=60)),
                ('provider', models.CharField(blank=True, default='', max_length=20)),
                ('provider_ref', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('problem', models.CharField(blank=True, default='', max_length=300)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('review', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_orders', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.merchant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('mobiles', 'Mobiles & tablets'), ('electronics', 'Electronics'), ('fashion_w', "Women's fashion"), ('fashion_m', "Men's fashion"), ('home', 'Home & kitchen'), ('beauty', 'Beauty & health'), ('grocery', 'Grocery'), ('baby', 'Baby & toys'), ('sports', 'Sports & outdoors'), ('books', 'Books & stationery'), ('auto', 'Car & bike'), ('industrial', 'Business & industrial'), ('other', 'Other')], db_index=True, default='other', max_length=12)),
                ('description', models.TextField(max_length=6000)),
                ('price', models.PositiveIntegerField()),
                ('old_price', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('images', models.JSONField(blank=True, default=list)),
                ('cod', models.BooleanField(default=True)),
                ('online', models.BooleanField(default=False)),
                ('delivery_fee', models.PositiveIntegerField(default=0)),
                ('delivery_days', models.PositiveSmallIntegerField(default=3)),
                ('sku', models.CharField(blank=True, default='', max_length=40)),
                ('cost_price', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('wholesale_price', models.PositiveIntegerField(default=0)),
                ('moq', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('hidden', models.BooleanField(db_index=True, default=False)),
                ('sold', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('rating_sum', models.PositiveIntegerField(default=0)),
                ('rating_n', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.merchant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('message', models.CharField(blank=True, default='', max_length=1000)),
                ('company', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('reply_price', models.PositiveIntegerField(default=0)),
                ('reply', models.CharField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(default='open', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_quotes', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='store.product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return / cancel'), ('adjust', 'Adjustment'), ('opening', 'Opening stock')], max_length=8)),
                ('qty', models.IntegerField()),
                ('unit', models.PositiveIntegerField(default=0)),
                ('party', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='store.product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('text', models.CharField(blank=True, default='', max_length=800)),
                ('reply', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('order', 'product')},
            },
        ),
    ]
