# Generated by Django 5.2.17 on 2026-10-10 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('kind', models.CharField(db_index=True, max_length=7)),
                ('source', models.CharField(db_index=True, max_length=12)),
                ('category', models.CharField(db_index=True, max_length=60)),
                ('amount', models.PositiveIntegerField()),
                ('ref', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('test', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-day', '-id'],
            },
        ),
    ]
