# Generated by Django 5.2.17 on 2026-09-24 07:53

import django.db.models.deletion
import django.utils.timezone
import pets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('other', 'Other')], max_length=10)),
                ('vaccine_name', models.CharField(max_length=150)),
                ('due_at_weeks', models.PositiveIntegerField(help_text='Age in weeks when it is due')),
                ('repeat_every_days', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'ordering': ['species', 'due_at_weeks', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('other', 'Other')], default='dog', max_length=10)),
                ('breed', models.CharField(blank=True, default='', max_length=80)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Not sure')], default='unknown', max_length=8)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, default='', max_length=120)),
                ('bio', models.TextField(blank=True, default='', max_length=1000)),
                ('tag_code', models.CharField(default=pets.models.new_tag, editable=False, max_length=12, unique=True)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('is_lost', models.BooleanField(db_index=True, default=False)),
                ('lost_since', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LostFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=6)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('other', 'Other')], default='dog', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('photo', models.CharField(blank=True, default='', max_length=120)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('where', models.CharField(blank=True, default='', max_length=200)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('expired', 'Expired')], db_index=True, default='active', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=pets.models.in_60_days)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_reports', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='pets.pet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vaccine', 'Vaccine'), ('checkup', 'Check-up'), ('deworming', 'Deworming'), ('medicine', 'Medicine'), ('weight', 'Weight'), ('other', 'Other')], default='other', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True, default='', max_length=1000)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('done', models.BooleanField(default=True)),
                ('next_due', models.DateField(blank=True, db_index=True, null=True)),
                ('repeat_days', models.PositiveIntegerField(blank=True, null=True)),
                ('reminded_for', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='pets.pet')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FoundNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_notes', to='pets.pet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
