# Generated by Django 5.2.17 on 2026-09-25 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('other', 'Other')], default='cat', max_length=10)),
                ('breed', models.CharField(blank=True, default='', max_length=80)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Not sure')], default='unknown', max_length=8)),
                ('age_text', models.CharField(blank=True, default='', max_length=40)),
                ('vaccinated', models.BooleanField(default=False)),
                ('neutered', models.BooleanField(default=False)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('adopted', 'Adopted'), ('closed', 'Closed')], db_index=True, default='available', max_length=10)),
                ('hidden', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_posts', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoption_posts', to='pets.pet')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VetClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=250)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('hours', models.CharField(blank=True, default='', max_length=120)),
                ('services', models.CharField(blank=True, default='', max_length=300)),
                ('emergency', models.BooleanField(default=False, help_text='Open for emergencies around the clock')),
                ('map_url', models.URLField(blank=True, default='', max_length=300)),
                ('approved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Waiting'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='pets.adoptionpost')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('post', 'requester')},
            },
        ),
    ]
