# Generated by Django 5.2.17 on 2026-10-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afsanay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afsana',
            name='review_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='afsana',
            name='status',
            field=models.CharField(db_index=True, default='published', max_length=10),
        ),
        migrations.AddField(
            model_name='qist',
            name='approved',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='qist',
            name='flag',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
