# Generated by Django 5.2.17 on 2026-10-01 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_day', models.DateField(blank=True, null=True)),
                ('days', models.PositiveIntegerField(default=0)),
                ('best', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.PositiveIntegerField()),
                ('box', models.PositiveSmallIntegerField(default=0)),
                ('due', models.DateField()),
                ('seen', models.PositiveIntegerField(default=0)),
                ('right', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
    ]
