# Generated by Django 5.2.17 on 2026-09-25 20:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('category', models.CharField(db_index=True, default='other', max_length=20)),
                ('method', models.CharField(blank=True, default='', max_length=7)),
                ('path', models.CharField(blank=True, default='', max_length=200)),
                ('object_id', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('agent', models.CharField(blank=True, default='', max_length=160)),
                ('extra', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='auditlog_au_user_id_0fb64f_idx')],
            },
        ),
    ]
