# Generated by Django 5.2.17 on 2026-09-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_proprofile_verified_proprofile_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='socials',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
