# Generated by Django 5.2.17 on 2026-08-11 04:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('relation', models.CharField(choices=[('family', 'Family'), ('parent', 'Parent'), ('sibling', 'Brother or sister'), ('child', 'Son or daughter'), ('spouse', 'Husband or wife'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('other', 'Other')], default='friend', max_length=20)),
                ('day', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('days_before', models.PositiveSmallIntegerField(default=3)),
                ('remind_on_day', models.BooleanField(default=True)),
                ('last_advance_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_dayof_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthdays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['month', 'day', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('advance', 'Days before'), ('day_of', 'On the day')], max_length=10)),
                ('for_year', models.PositiveSmallIntegerField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ok', models.BooleanField(default=True)),
                ('birthday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='reminders.birthday')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='birthday',
            index=models.Index(fields=['month', 'day'], name='reminders_b_month_1969a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sent',
            unique_together={('birthday', 'kind', 'for_year')},
        ),
    ]
