# Generated by Django 5.2.17 on 2026-10-10 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('days', models.PositiveSmallIntegerField()),
                ('note', models.TextField(max_length=1500)),
                ('status', models.CharField(default='sent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['amount', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('design', 'Design'), ('writing', 'Writing & translation'), ('web', 'Websites & apps'), ('marketing', 'Digital marketing'), ('video', 'Video & animation'), ('office', 'Office, data & Excel'), ('teaching', 'Teaching & tutoring'), ('business', 'Business & accounts'), ('other', 'Other')], db_index=True, default='other', max_length=12)),
                ('description', models.TextField(max_length=4000)),
                ('price', models.PositiveIntegerField()),
                ('days', models.PositiveSmallIntegerField(default=3)),
                ('revisions', models.PositiveSmallIntegerField(default=1)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('hidden', models.BooleanField(db_index=True, default=False)),
                ('orders_done', models.PositiveIntegerField(default=0)),
                ('rating_sum', models.PositiveIntegerField(default=0)),
                ('rating_n', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('amount', models.PositiveIntegerField()),
                ('fee', models.PositiveIntegerField()),
                ('days', models.PositiveSmallIntegerField()),
                ('revisions_left', models.PositiveSmallIntegerField(default=1)),
                ('requirements', models.TextField(blank=True, default='', max_length=3000)),
                ('status', models.CharField(db_index=True, default='pending', max_length=12)),
                ('provider', models.CharField(blank=True, default='', max_length=20)),
                ('provider_ref', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('delivery', models.TextField(blank=True, default='', max_length=3000)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('bid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='market.bid')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_buys', to=settings.AUTH_USER_MODEL)),
                ('gig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='market.gig')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='market.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('easypaisa', 'EasyPaisa'), ('jazzcash', 'JazzCash'), ('bank', 'Bank account')], max_length=10)),
                ('account_name', models.CharField(max_length=80)),
                ('account_no', models.CharField(max_length=40)),
                ('bank', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(db_index=True, default='requested', max_length=10)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('design', 'Design'), ('writing', 'Writing & translation'), ('web', 'Websites & apps'), ('marketing', 'Digital marketing'), ('video', 'Video & animation'), ('office', 'Office, data & Excel'), ('teaching', 'Teaching & tutoring'), ('business', 'Business & accounts'), ('other', 'Other')], db_index=True, default='other', max_length=12)),
                ('description', models.TextField(max_length=4000)),
                ('budget', models.PositiveIntegerField()),
                ('days', models.PositiveSmallIntegerField(default=7)),
                ('status', models.CharField(db_index=True, default='open', max_length=10)),
                ('hidden', models.BooleanField(db_index=True, default=False)),
                ('bids_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='market.project'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('text', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='market.order')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('kind', models.CharField(max_length=12)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_entries', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='market.order')),
            ],
            options={
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'earning')), fields=('order', 'kind'), name='market_entry_once')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('project', 'seller')},
        ),
    ]
