# Generated by Django 5.2.17 on 2026-10-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
