# Generated by Django 5.2.17 on 2026-10-02 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0009_chatmessage_voice_chatmessage_voice_secs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('only', models.CharField(default='', max_length=8)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xrule', to='notifications.chatgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Pref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, default='', max_length=8)),
                ('find', models.CharField(default='everyone', max_length=12)),
                ('requests', models.CharField(default='everyone', max_length=12)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xpref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
