# Generated by Django 5.2.17 on 2026-10-09 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.PositiveIntegerField(default=8000)),
                ('height_cm', models.PositiveSmallIntegerField(default=168)),
                ('weight_kg', models.PositiveSmallIntegerField(default=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='walk', max_length=8)),
                ('started_at', models.DateTimeField()),
                ('day', models.DateField(db_index=True)),
                ('secs', models.PositiveIntegerField(default=0)),
                ('steps', models.PositiveIntegerField(default=0)),
                ('steps_est', models.BooleanField(default=False)),
                ('dist_m', models.PositiveIntegerField(default=0)),
                ('kcal', models.PositiveIntegerField(default=0)),
                ('path', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_walks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'started_at'), name='steps_walk_once')],
            },
        ),
    ]
