# Generated by Django 5.2.17 on 2026-10-10 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('sale', 'For sale'), ('rent', 'For rent')], db_index=True, default='sale', max_length=4)),
                ('kind', models.CharField(choices=[('house', 'House'), ('flat', 'Flat / apartment'), ('plot', 'Plot'), ('commercial', 'Shop / commercial'), ('office', 'Office'), ('farmhouse', 'Farmhouse'), ('room', 'Room / portion'), ('land', 'Agricultural land')], db_index=True, default='house', max_length=12)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=5000)),
                ('price', models.BigIntegerField()),
                ('city', models.CharField(db_index=True, max_length=60)),
                ('locality', models.CharField(max_length=120)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('marla', 'Marla'), ('kanal', 'Kanal'), ('sqft', 'Sq. ft.'), ('sqyd', 'Sq. yd.'), ('acre', 'Acre')], default='marla', max_length=6)),
                ('bedrooms', models.PositiveSmallIntegerField(default=0)),
                ('bathrooms', models.PositiveSmallIntegerField(default=0)),
                ('furnished', models.BooleanField(default=False)),
                ('by_agent', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=20)),
                ('images', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(db_index=True, default='active', max_length=8)),
                ('hidden', models.BooleanField(db_index=True, default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('reports', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('renewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-renewed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_rows', to='realestate.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('listing', 'user')},
            },
        ),
    ]
