# Generated by Django 5.2.17 on 2026-08-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_from_leaderboard',
            field=models.BooleanField(default=False, help_text='When set, this user is ranked but never named publicly.'),
        ),
    ]
