# Generated by Django 5.2.17 on 2026-08-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_hide_from_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
