# Generated by Django 5.2.17 on 2026-08-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_birth_day_user_birth_month_user_birth_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vibe',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
