# Generated by Django 5.2.17 on 2026-08-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_vibe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
