# Generated by Django 5.2.17 on 2026-08-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_signup_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_moderator',
            field=models.BooleanField(default=False, help_text='Can moderate review comments. Cannot appoint others.'),
        ),
        migrations.AddField(
            model_name='user',
            name='moderator_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
