# Generated by Django 5.2.17 on 2026-08-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_moderator_user_moderator_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_whatsapp_on_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
