"""
Django settings for xpertapi project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

def env(key, default=""):
    """Read from .env sitting next to manage.py. Secrets never live in code."""
    path = BASE_DIR / ".env"
    if not hasattr(env, "_cache"):
        env._cache = {}
        if path.exists():
            for line in path.read_text().splitlines():
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    env._cache[k.strip()] = v.strip().strip('"').strip("'")
    return os.environ.get(key) or env._cache.get(key, default)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", "0") == "1"

ALLOWED_HOSTS = [h.strip() for h in env("ALLOWED_HOSTS", "learn.xpertcreation.com,xpertcreation.com,www.xpertcreation.com").split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "rest_framework",
    "corsheaders",
    "accounts",
    "academy",
    "typingtutor",
    "bloodbank",
    "reminders",
    "weather",
    "games",
    "news",
    "reviews",
    "geo",
    "moderation",
    "vcard",
    "network",
    "pets",
    "screen",
    "auditlog",
    "jobs",
    "feed",
    "donations",
    "notifications",
    "botlink",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "auditlog.middleware.AuditMiddleware",
    'accounts.presence.PresenceMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'xpertapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xpertapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME", "xpertapi"),
        "USER": env("DB_USER", "xpertapi"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST", "127.0.0.1"),
        "PORT": env("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Karachi"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/django-static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------------
# XpertCreation API
# ---------------------------------------------------------------------------

AUTH_USER_MODEL = "accounts.User"

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
     "OPTIONS": {"min_length": 8}},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [],
    "DEFAULT_THROTTLE_RATES": {
        "chat": "60/min",
        "login": "8/hour",
        "register": "5/hour",
        "code_send": "6/hour",
        "code_check": "15/hour",
        "quiz": "20/hour",
        "verify": "60/hour",
        # Answers are cached for ten minutes, so this is far more
        # than anyone needs and still bounds a scraper.
        "weather": "60/hour",
        # Cached for fifteen minutes, so this only bounds a scraper.
        "news": "60/hour",
        # One review per module per person, so this only stops
        # somebody hammering the endpoint.
        "reviews": "30/hour",
        "geo": "120/hour",
        # Professional network
        "net_edit": "300/hour",
        "net_endorse": "60/hour",
        "net_report": "10/hour",
        "net_browse": "600/hour",
        "net_connect": "60/hour",
        "net_follow": "120/hour",
        # Pets
        "pets_edit": "300/hour",
        "pets_found": "20/hour",
        "pets_lost": "30/day",
        "pets_browse": "600/hour",
        "jobs_post": "10/hour",
        "jobs_apply": "30/hour",
        "feed_post": "20/hour",
        "feed_react": "300/hour",
        "feed_comment": "60/hour",
        # Shows
        "screen_browse": "600/hour",
        "screen_write": "120/hour",
        "botcode": "10/hour",
        # Posting a donation listing.
        "donate_post": "10/hour",
        "donate_request": "30/hour",
        "ticket": "60/hour",
        "modapply": "5/day",
        "feedback": "5/day",
        # Starting a game is cheap; this only bounds a script that
        # tries to farm the leaderboard by opening games in a loop.
        "games": "120/hour",
        # A run takes at least a few seconds, so this is generous for a
        # person and tight for a script.
        "typing": "120/hour",
        # Search is signed-in only; this keeps a curious account from
        # paging through the whole donor list.
        "blood_search": "60/hour",
        "blood_ask": "40/hour",
    },
}

# Throttling needs a shared cache. LocMemCache is per-process, so each gunicorn
# worker would keep its own counter and every limit would be multiplied by the
# worker count - which makes brute-force protection decorative.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": env("REDIS_URL", "redis://127.0.0.1:6379/3"),
    }
}

SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14
SESSION_COOKIE_NAME = "xc_session"
# Shared across every subdomain, so one sign-in covers the whole site.
# Note this also means a compromise of ANY subdomain exposes the session:
# never point an untrusted or user-controlled host at this domain.
SESSION_COOKIE_DOMAIN = ".xpertcreation.com"
CSRF_COOKIE_DOMAIN = ".xpertcreation.com"
# Renamed so the pre-existing host-only "csrftoken" cookie cannot be
# picked up by mistake and sent as the wrong token.
CSRF_COOKIE_NAME = "xc_csrf"

CSRF_COOKIE_SECURE = True
# XpertLoad sits on its own subdomain and asks the main domain who is
# signed in. Only our own hosts are listed; credentials are allowed, so
# a wildcard here would be a serious mistake.
CORS_ALLOWED_ORIGINS = [
    "https://load.xpertcreation.com",
    "https://learn.xpertcreation.com",
    "https://xpertcreation.com",
]
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "https://learn.xpertcreation.com",
    "https://load.xpertcreation.com",
    "https://xpertcreation.com",
]

# Behind nginx and Cloudflare.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

OPENWEATHER_KEY = env("OPENWEATHER_KEY")

FEEDBACK_TO = env("FEEDBACK_TO", "khalid@xpertcreation.com")

SITE_URL = env("SITE_URL", "https://learn.xpertcreation.com")
CERTIFICATE_SIGNATURE_URL = env("CERTIFICATE_SIGNATURE_URL", "/brand/signature.jpg")

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env("EMAIL_HOST", "mail.xpertcreation.com")
EMAIL_PORT = int(env("EMAIL_PORT", "465"))
EMAIL_USE_SSL = env("EMAIL_USE_SSL", "1") == "1"
EMAIL_USE_TLS = not EMAIL_USE_SSL
EMAIL_HOST_USER = env("EMAIL_HOST_USER", "no_reply@xpertcreation.com")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", "")
# Login address and From address must match, or many SMTP servers reject the
# message and the rest score it as spam.
DEFAULT_FROM_EMAIL = "XpertAcademy <%s>" % EMAIL_HOST_USER

STATIC_ROOT = BASE_DIR / "staticfiles"


# Donation photos live here, served by nginx directly (not through gunicorn).
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# The same shared-secret pattern PenFlow already uses for its own
# Discord integration: the bot authenticates with this, not a user
# login, when it calls back to confirm a link.
DISCORD_BOT_SECRET = env("XC_DISCORD_BOT_SECRET", "")
TELEGRAM_BOT_SECRET = env("XC_TELEGRAM_BOT_SECRET", "")
