# Generated by Django 5.2.17 on 2026-08-17 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('org', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=60)),
                ('show_phone', models.BooleanField(default=False)),
                ('show_email', models.BooleanField(default=True)),
                ('show_whatsapp', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=32)),
                ('linkedin', models.URLField(blank=True, default='')),
                ('instagram', models.URLField(blank=True, default='')),
                ('twitter', models.URLField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('theme', models.CharField(choices=[('ink', 'Midnight'), ('emerald', 'Emerald'), ('rose', 'Rose'), ('amber', 'Amber')], default='ink', max_length=12)),
                ('token', models.SlugField(editable=False, max_length=24, unique=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visiting_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
