# Generated by Django 5.2.17 on 2026-10-02 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('job', 'Govt job'), ('result', 'Result'), ('admission', 'Admission'), ('scholarship', 'Scholarship')], db_index=True, max_length=12)),
                ('title', models.CharField(max_length=160)),
                ('org', models.CharField(blank=True, default='', max_length=120)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('link', models.URLField(max_length=400)),
                ('details', models.TextField(blank=True, default='', max_length=2000)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
