# Generated by Django 5.2.17 on 2026-08-17 10:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('books', 'Books'), ('clothes', 'Clothes'), ('shoes', 'Shoes'), ('furniture', 'Furniture'), ('electronics', 'Electronics'), ('toys', 'Toys'), ('kitchen', 'Kitchen & household'), ('other', 'Other')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('condition', models.CharField(choices=[('new', 'New / unused'), ('good', 'Good condition'), ('fair', 'Well used but usable')], default='good', max_length=10)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('city', models.CharField(db_index=True, max_length=60)),
                ('state', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('given', 'Given away'), ('removed', 'Removed')], db_index=True, default='available', max_length=10)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('given_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='donations/%Y/%m/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='donations.donationitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DonationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('handled', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='donations.donationitem')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='', max_length=300)),
                ('state', models.CharField(choices=[('pending', 'Waiting'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='donations.donationitem')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='donationitem',
            index=models.Index(fields=['category', 'state', 'city'], name='donations_d_categor_5f95e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='donationrequest',
            unique_together={('item', 'requester')},
        ),
    ]
