# Generated by Django 5.2.17 on 2026-08-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationitem',
            name='category',
            field=models.CharField(choices=[('books', 'Books'), ('clothes', 'Clothes'), ('shoes', 'Shoes'), ('furniture', 'Furniture'), ('electronics', 'Electronics'), ('toys', 'Toys'), ('kitchen', 'Kitchen & household'), ('pets', 'Pet supplies'), ('other', 'Other')], db_index=True, max_length=20),
        ),
    ]
