# Generated by Django 5.2.17 on 2026-10-10 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('car', 'Car'), ('rickshaw', 'Rickshaw'), ('bike', 'Bike')], max_length=10, unique=True)),
                ('base', models.PositiveIntegerField(default=100)),
                ('per_km', models.PositiveIntegerField(default=40)),
                ('minimum', models.PositiveIntegerField(default=150)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Waiting for review'), ('approved', 'Approved'), ('rejected', 'Not approved'), ('suspended', 'Suspended')], db_index=True, default='draft', max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=60)),
                ('vehicle', models.CharField(choices=[('car', 'Car'), ('rickshaw', 'Rickshaw'), ('bike', 'Bike')], max_length=10)),
                ('make', models.CharField(max_length=60)),
                ('plate', models.CharField(max_length=20)),
                ('licence_no', models.CharField(blank=True, default='', max_length=30)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('online', models.BooleanField(db_index=True, default=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('loc_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.FloatField(default=0)),
                ('ratings', models.PositiveIntegerField(default=0)),
                ('rides_done', models.PositiveIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ride_driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('licence', 'Driving licence'), ('registration', 'Vehicle registration'), ('selfie', 'Photo with the vehicle'), ('other', 'Other')], max_length=14)),
                ('path', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='rides.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('car', 'Car'), ('rickshaw', 'Rickshaw'), ('bike', 'Bike')], max_length=10)),
                ('status', models.CharField(choices=[('searching', 'Finding a driver'), ('accepted', 'Driver on the way'), ('arrived', 'Driver has arrived'), ('started', 'On the trip'), ('done', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'No driver found')], db_index=True, default='searching', max_length=10)),
                ('p_lat', models.FloatField()),
                ('p_lng', models.FloatField()),
                ('p_text', models.CharField(blank=True, default='', max_length=160)),
                ('d_lat', models.FloatField()),
                ('d_lng', models.FloatField()),
                ('d_text', models.CharField(blank=True, default='', max_length=160)),
                ('km', models.FloatField(default=0)),
                ('fare', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('skip', models.JSONField(blank=True, default=list)),
                ('token', models.CharField(max_length=24, unique=True)),
                ('cancel_by', models.CharField(blank=True, default='', max_length=10)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=200)),
                ('rider_stars', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('driver_stars', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='rides.driver')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_taken', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sos', models.BooleanField(default=False)),
                ('text', models.CharField(blank=True, default='', max_length=600)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='rides.ride')),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('agreed_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0)),
                ('ratings', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ride_rider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
