# Generated by Django 5.2.17 on 2026-08-10 15:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('lesson', 'Lesson'), ('test', 'Test'), ('game', 'Game')], default='lesson', max_length=10)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=120)),
                ('hint', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField()),
                ('lang', models.CharField(default='en', max_length=5)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'level', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=32, unique=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typingtutor.drill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_wpm', models.PositiveSmallIntegerField(default=0)),
                ('best_accuracy', models.PositiveSmallIntegerField(default=0)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('total_seconds', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveSmallIntegerField(default=0)),
                ('longest_streak', models.PositiveSmallIntegerField(default=0)),
                ('last_day', models.DateField(blank=True, null=True)),
                ('lessons_done', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='typing_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('lesson', 'Lesson'), ('test', 'Test'), ('game', 'Game')], default='test', max_length=10)),
                ('wpm', models.PositiveSmallIntegerField()),
                ('accuracy', models.PositiveSmallIntegerField()),
                ('correct_chars', models.PositiveIntegerField(default=0)),
                ('typed_chars', models.PositiveIntegerField(default=0)),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('drill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='typingtutor.drill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-wpm', 'created_at'],
                'indexes': [models.Index(fields=['mode', '-wpm'], name='typingtutor_mode_b6e2bf_idx'), models.Index(fields=['user', '-created_at'], name='typingtutor_user_id_02f51b_idx')],
            },
        ),
    ]
