# Generated by Django 5.2.17 on 2026-08-16 06:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('academy', 'XpertAcademy'), ('blood', 'Blood Bank'), ('typing', 'Typing Tutor'), ('games', 'Games'), ('birthdays', 'Birthday Reminders'), ('weather', 'Weather'), ('zodiac', 'Star signs'), ('vibe', 'Vibe check')], db_index=True, max_length=20)),
                ('stars', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, default='', max_length=600)),
                ('state', models.CharField(choices=[('pending', 'Waiting'), ('published', 'Published'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'state', '-created_at'], name='reviews_rev_module_b45997_idx')],
                'unique_together': {('user', 'module')},
            },
        ),
    ]
