# Generated by Django 5.2.17 on 2026-10-09 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_prizeslot_rewardentry_spin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='facebook_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='campaign',
            name='youtube_url',
            field=models.CharField(blank=True, default='https://www.youtube.com/@XpertCreationPK?sub_confirmation=1', max_length=200),
        ),
        migrations.CreateModel(
            name='RewardSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('post_id', models.PositiveIntegerField(blank=True, null=True)),
                ('post_at', models.DateTimeField(blank=True, null=True)),
                ('irc_at', models.DateTimeField(blank=True, null=True)),
                ('youtube_at', models.DateTimeField(blank=True, null=True)),
                ('facebook_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('easypaisa', 'EasyPaisa'), ('jazzcash', 'JazzCash'), ('bank', 'Bank transfer'), ('load', 'Mobile load'), ('other', 'Other (arrange with admin)')], max_length=10)),
                ('country', models.CharField(default='PK', max_length=2)),
                ('account_name', models.CharField(blank=True, default='', max_length=80)),
                ('account_no', models.CharField(blank=True, default='', max_length=40)),
                ('account_key', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('bank_name', models.CharField(blank=True, default='', max_length=80)),
                ('network', models.CharField(blank=True, default='', max_length=20)),
                ('details', models.TextField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('requested', 'Waiting'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=10)),
                ('admin_note', models.CharField(blank=True, default='', max_length=300)),
                ('proof_path', models.CharField(blank=True, default='', max_length=200)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
