# Generated by Django 5.2.17 on 2026-10-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_campaign_facebook_url_campaign_youtube_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='card_pin',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='loaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='revealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='method',
            field=models.CharField(choices=[('easypaisa', 'EasyPaisa'), ('jazzcash', 'JazzCash'), ('bank', 'Bank transfer'), ('load', 'Mobile load'), ('scratch', 'Scratch card'), ('other', 'Other (arrange with admin)')], max_length=10),
        ),
    ]
