# Generated by Django 5.2.17 on 2026-08-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('bug', 'Something is broken'), ('account', 'Account or sign-in'), ('content', 'A course or a certificate'), ('feature', "A feature I'd like"), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'Being looked at'), ('answered', 'Answered'), ('closed', 'Closed')], db_index=True, default='open', max_length=15),
        ),
    ]
