from django.core.management.base import BaseCommand
from django.db import transaction

from academy.models import Choice, Course, Lesson, Question

COURSES = [{'slug': 'word',
  'title': 'Microsoft Word',
  'icon': '📝',
  'accent': '#2B579A',
  'blurb': 'Write, format and print professional documents — letters, CVs, reports and '
           'assignments.',
  'order': 0,
  'lessons': [{'key': 'the-word-window', 'title': 'The Word window', 'minutes': 6, 'order': 0},
              {'key': 'typing-selecting-and-editing',
               'title': 'Typing, selecting and editing',
               'minutes': 8,
               'order': 1},
              {'key': 'formatting-text', 'title': 'Formatting text', 'minutes': 8, 'order': 2},
              {'key': 'paragraphs-alignment-and-spacing',
               'title': 'Paragraphs, alignment and spacing',
               'minutes': 7,
               'order': 3},
              {'key': 'bullets-and-numbered-lists',
               'title': 'Bullets and numbered lists',
               'minutes': 6,
               'order': 4},
              {'key': 'tables', 'title': 'Tables', 'minutes': 8, 'order': 5},
              {'key': 'page-setup-and-printing',
               'title': 'Page setup and printing',
               'minutes': 7,
               'order': 6}]},
 {'slug': 'excel',
  'title': 'Microsoft Excel',
  'icon': '📊',
  'accent': '#217346',
  'blurb': 'From your very first cell to lookups and pivot tables — with real spreadsheets you '
           'build as you go.',
  'order': 1,
  'lessons': [{'key': 'what-a-spreadsheet-actually-is',
               'title': 'What a spreadsheet actually is',
               'minutes': 7,
               'order': 0},
              {'key': 'entering-data-text-numbers-dates',
               'title': 'Entering data: text, numbers, dates',
               'minutes': 8,
               'order': 1},
              {'key': 'editing-and-the-fill-handle',
               'title': 'Editing and the fill handle',
               'minutes': 7,
               'order': 2},
              {'key': 'your-first-formula',
               'title': 'Your first formula',
               'minutes': 8,
               'order': 3},
              {'key': 'sum-average-count-min-max',
               'title': 'SUM, AVERAGE, COUNT, MIN, MAX',
               'minutes': 9,
               'order': 4},
              {'key': 'worked-example-monthly-budget',
               'title': 'Worked example: monthly budget',
               'minutes': 12,
               'order': 5},
              {'key': 'absolute-references-and-the-dollar-sign',
               'title': 'Absolute references and the dollar sign',
               'minutes': 10,
               'order': 6},
              {'key': 'number-formatting-pkr-dates-percentages',
               'title': 'Number formatting: PKR, dates, percentages',
               'minutes': 8,
               'order': 7},
              {'key': 'if-making-the-sheet-decide',
               'title': 'IF: making the sheet decide',
               'minutes': 10,
               'order': 8},
              {'key': 'countif-and-sumif', 'title': 'COUNTIF and SUMIF', 'minutes': 9, 'order': 9},
              {'key': 'vlookup-and-xlookup',
               'title': 'VLOOKUP and XLOOKUP',
               'minutes': 11,
               'order': 10},
              {'key': 'worked-example-student-result-sheet',
               'title': 'Worked example: student result sheet',
               'minutes': 12,
               'order': 11},
              {'key': 'sorting-filtering-and-tables',
               'title': 'Sorting, filtering and Tables',
               'minutes': 8,
               'order': 12},
              {'key': 'conditional-formatting-and-dropdowns',
               'title': 'Conditional formatting and dropdowns',
               'minutes': 9,
               'order': 13},
              {'key': 'charts-that-explain-themselves',
               'title': 'Charts that explain themselves',
               'minutes': 9,
               'order': 14},
              {'key': 'pivottables', 'title': 'PivotTables', 'minutes': 11, 'order': 15}]},
 {'slug': 'powerpoint',
  'title': 'Microsoft PowerPoint',
  'icon': '📽️',
  'accent': '#B7472A',
  'blurb': 'Build slides people actually follow — for class, for work, and for pitching an idea.',
  'order': 2,
  'lessons': [{'key': 'slides-and-layouts',
               'title': 'Slides and layouts',
               'minutes': 6,
               'order': 0},
              {'key': 'text-that-works-on-a-slide',
               'title': 'Text that works on a slide',
               'minutes': 7,
               'order': 1},
              {'key': 'images-and-shapes', 'title': 'Images and shapes', 'minutes': 7, 'order': 2},
              {'key': 'themes-and-colour', 'title': 'Themes and colour', 'minutes': 6, 'order': 3},
              {'key': 'transitions-and-animation',
               'title': 'Transitions and animation',
               'minutes': 6,
               'order': 4},
              {'key': 'presenting-and-exporting',
               'title': 'Presenting and exporting',
               'minutes': 7,
               'order': 5}]},
 {'slug': 'vba',
  'title': 'Excel VBA & Macros',
  'icon': '⚙️',
  'accent': '#0F766E',
  'blurb': 'Automate the boring parts of Excel. Record your first macro, then learn to read and '
           'write the code yourself.',
  'order': 3,
  'lessons': [{'key': 'what-vba-is-and-when-to-use-it',
               'title': 'What VBA is, and when to use it',
               'minutes': 8,
               'order': 0},
              {'key': 'setting-up-the-developer-tab-and-xlsm',
               'title': 'Setting up: the Developer tab and .xlsm',
               'minutes': 8,
               'order': 1},
              {'key': 'recording-your-first-macro',
               'title': 'Recording your first macro',
               'minutes': 9,
               'order': 2},
              {'key': 'reading-the-code-you-recorded',
               'title': 'Reading the code you recorded',
               'minutes': 10,
               'order': 3},
              {'key': 'writing-code-yourself',
               'title': 'Writing code yourself',
               'minutes': 10,
               'order': 4},
              {'key': 'variables-and-loops',
               'title': 'Variables and loops',
               'minutes': 11,
               'order': 5},
              {'key': 'if-then-and-error-handling',
               'title': 'If, Then, and error handling',
               'minutes': 10,
               'order': 6},
              {'key': 'worked-example-a-report-cleaner-with-a-button',
               'title': 'Worked example: a report cleaner with a button',
               'minutes': 13,
               'order': 7}]},
 {'slug': 'alquran',
  'title': 'قرآنی عربی',
  'icon': '📖',
  'accent': '#B8892D',
  'blurb': 'قرآنی عربی کے تیس مختصر روزانہ اسباق: الفاظ، بنیادی قواعد، اور چھوٹی عبارتیں لفظ بہ '
           'لفظ پڑھنا۔',
  'order': 4,
  'lessons': [{'key': 'day-1', 'title': 'دن 1 سبق — قرآنی عربی', 'minutes': 30, 'order': 0},
              {'key': 'day-2', 'title': 'دن 2 سبق — قرآنی عربی', 'minutes': 30, 'order': 1},
              {'key': 'day-3', 'title': 'دن 3 سبق — قرآنی عربی', 'minutes': 30, 'order': 2},
              {'key': 'day-4', 'title': 'دن 4 سبق — قرآنی عربی', 'minutes': 30, 'order': 3},
              {'key': 'day-5', 'title': 'دن 5 سبق — قرآنی عربی', 'minutes': 30, 'order': 4},
              {'key': 'day-6', 'title': 'دن 6 سبق — قرآنی عربی', 'minutes': 30, 'order': 5},
              {'key': 'day-7', 'title': 'دن 7 سبق — قرآنی عربی', 'minutes': 30, 'order': 6},
              {'key': 'day-8', 'title': 'دن 8 سبق — قرآنی عربی', 'minutes': 30, 'order': 7},
              {'key': 'day-9', 'title': 'دن 9 سبق — قرآنی عربی', 'minutes': 30, 'order': 8},
              {'key': 'day-10', 'title': 'دن 10 سبق — قرآنی عربی', 'minutes': 30, 'order': 9},
              {'key': 'day-11', 'title': 'دن 11 سبق — قرآنی عربی', 'minutes': 30, 'order': 10},
              {'key': 'day-12', 'title': 'دن 12 سبق — قرآنی عربی', 'minutes': 30, 'order': 11},
              {'key': 'day-13', 'title': 'دن 13 سبق — قرآنی عربی', 'minutes': 30, 'order': 12},
              {'key': 'day-14', 'title': 'دن 14 سبق — قرآنی عربی', 'minutes': 30, 'order': 13},
              {'key': 'day-15', 'title': 'دن 15 سبق — قرآنی عربی', 'minutes': 30, 'order': 14},
              {'key': 'day-16', 'title': 'دن 16 سبق — قرآنی عربی', 'minutes': 30, 'order': 15},
              {'key': 'day-17', 'title': 'دن 17 سبق — قرآنی عربی', 'minutes': 30, 'order': 16},
              {'key': 'day-18', 'title': 'دن 18 سبق — قرآنی عربی', 'minutes': 30, 'order': 17},
              {'key': 'day-19', 'title': 'دن 19 سبق — قرآنی عربی', 'minutes': 30, 'order': 18},
              {'key': 'day-20', 'title': 'دن 20 سبق — قرآنی عربی', 'minutes': 30, 'order': 19},
              {'key': 'day-21', 'title': 'دن 21 سبق — قرآنی عربی', 'minutes': 30, 'order': 20},
              {'key': 'day-22', 'title': 'دن 22 سبق — قرآنی عربی', 'minutes': 30, 'order': 21},
              {'key': 'day-23', 'title': 'دن 23 سبق — قرآنی عربی', 'minutes': 30, 'order': 22},
              {'key': 'day-24', 'title': 'دن 24 سبق — قرآنی عربی', 'minutes': 30, 'order': 23},
              {'key': 'day-25', 'title': 'دن 25 سبق — قرآنی عربی', 'minutes': 30, 'order': 24},
              {'key': 'day-26', 'title': 'دن 26 سبق — قرآنی عربی', 'minutes': 30, 'order': 25},
              {'key': 'day-27', 'title': 'دن 27 سبق — قرآنی عربی', 'minutes': 30, 'order': 26},
              {'key': 'day-28', 'title': 'دن 28 سبق — قرآنی عربی', 'minutes': 30, 'order': 27},
              {'key': 'day-29', 'title': 'دن 29 سبق — قرآنی عربی', 'minutes': 30, 'order': 28},
              {'key': 'day-30', 'title': 'دن 30 سبق — قرآنی عربی', 'minutes': 30, 'order': 29}]}]

QUIZ = {'word': [{'text': 'You are typing a paragraph and reach the right edge of the page. What should '
                   'you do?',
           'explanation': 'Word wraps automatically. Pressing Enter at the end of every line '
                          'creates separate paragraphs, and the text falls apart the moment you '
                          'edit or change the margins.',
           'order': 0,
           'choices': [{'text': 'Press Enter to start the next line',
                        'is_correct': False,
                        'order': 0},
                       {'text': 'Keep typing — Word wraps by itself',
                        'is_correct': True,
                        'order': 1},
                       {'text': 'Press Tab', 'is_correct': False, 'order': 2},
                       {'text': 'Insert a line break', 'is_correct': False, 'order': 3}]},
          {'text': 'Which shortcut undoes your last action?',
           'explanation': 'Ctrl+Z undoes. Ctrl+Y redoes. Ctrl+U underlines and Ctrl+X cuts.',
           'order': 1,
           'choices': [{'text': 'Ctrl+U', 'is_correct': False, 'order': 0},
                       {'text': 'Ctrl+Y', 'is_correct': False, 'order': 1},
                       {'text': 'Ctrl+Z', 'is_correct': True, 'order': 2},
                       {'text': 'Ctrl+X', 'is_correct': False, 'order': 3}]},
          {'text': "You paste text from a website and it brings the site's fonts and colours with "
                   'it. What is the fix?',
           'explanation': 'Ctrl+Shift+V pastes plain text. Right-click and Keep Text Only does the '
                          'same thing through the menu.',
           'order': 2,
           'choices': [{'text': 'Retype it by hand', 'is_correct': False, 'order': 0},
                       {'text': 'Paste, then manually reformat', 'is_correct': False, 'order': 1},
                       {'text': 'Use Ctrl+Shift+V, or Keep Text Only',
                        'is_correct': True,
                        'order': 2},
                       {'text': 'Change the theme', 'is_correct': False, 'order': 3}]},
          {'text': 'What does the Format Painter do?',
           'explanation': 'Click text that looks right, click the paintbrush, then drag over text '
                          'you want to match. Double-click the paintbrush to apply it repeatedly.',
           'order': 3,
           'choices': [{'text': 'Changes the page background', 'is_correct': False, 'order': 0},
                       {'text': 'Copies formatting from one piece of text to another',
                        'is_correct': True,
                        'order': 1},
                       {'text': 'Prints in colour', 'is_correct': False, 'order': 2},
                       {'text': 'Paints shapes', 'is_correct': False, 'order': 3}]},
          {'text': 'You are printing in Pakistan and the edges of your document are getting cut '
                   'off. What is the most likely cause?',
           'explanation': 'Word often defaults to Letter, an American size. A4 is standard in '
                          'Pakistan. Set Size to A4 on the Layout tab.',
           'order': 4,
           'choices': [{'text': 'The printer is faulty', 'is_correct': False, 'order': 0},
                       {'text': 'Page size is set to Letter instead of A4',
                        'is_correct': True,
                        'order': 1},
                       {'text': 'Margins are too wide', 'is_correct': False, 'order': 2},
                       {'text': 'The font is too large', 'is_correct': False, 'order': 3}]},
          {'text': 'What is the correct way to add space between paragraphs?',
           'explanation': 'Space After gives consistent spacing that does not shift when you edit. '
                          'Double Enters create empty paragraphs that behave unpredictably.',
           'order': 5,
           'choices': [{'text': 'Press Enter twice', 'is_correct': False, 'order': 0},
                       {'text': 'Set Space After in the Paragraph settings',
                        'is_correct': True,
                        'order': 1},
                       {'text': 'Add blank lines with Tab', 'is_correct': False, 'order': 2},
                       {'text': 'Increase the font size', 'is_correct': False, 'order': 3}]},
          {'text': 'In a numbered list, why should you never type the numbers yourself?',
           'explanation': 'Automatic numbering fixes itself when you insert or delete an item. '
                          'Typed numbers do not, and you end up with two number 4s.',
           'order': 6,
           'choices': [{'text': 'It is slower', 'is_correct': False, 'order': 0},
                       {'text': 'Word renumbers automatically when items are added or removed',
                        'is_correct': True,
                        'order': 1},
                       {'text': 'Numbers cannot be typed', 'is_correct': False, 'order': 2},
                       {'text': 'It changes the font', 'is_correct': False, 'order': 3}]},
          {'text': 'The Table Design and Layout tabs have disappeared. Why?',
           'explanation': 'Those tabs only appear when the cursor sits inside a table. Click into '
                          'any cell and they come back.',
           'order': 7,
           'choices': [{'text': 'They were removed', 'is_correct': False, 'order': 0},
                       {'text': 'Your cursor is not inside a table',
                        'is_correct': True,
                        'order': 1},
                       {'text': 'The document is read-only', 'is_correct': False, 'order': 2},
                       {'text': 'You need to reinstall Word', 'is_correct': False, 'order': 3}]},
          {'text': 'What does the paragraph mark button on the Home tab show you?',
           'explanation': 'It reveals the invisible characters. When formatting misbehaves, this '
                          'is how you see what is actually there.',
           'order': 8,
           'choices': [{'text': 'Paragraph numbering', 'is_correct': False, 'order': 0},
                       {'text': 'Hidden marks: spaces, tabs and paragraph breaks',
                        'is_correct': True,
                        'order': 1},
                       {'text': 'Page breaks only', 'is_correct': False, 'order': 2},
                       {'text': 'The word count', 'is_correct': False, 'order': 3}]},
          {'text': 'What is the safest way to send a document so it looks the same on every '
                   'computer?',
           'explanation': 'PDF locks the layout and fonts. A .docx can shift depending on which '
                          'fonts the recipient has installed.',
           'order': 9,
           'choices': [{'text': 'Send the .docx file', 'is_correct': False, 'order': 0},
                       {'text': 'Export it as a PDF', 'is_correct': True, 'order': 1},
                       {'text': 'Copy the text into an email', 'is_correct': False, 'order': 2},
                       {'text': 'Print and scan it', 'is_correct': False, 'order': 3}]}],
 'powerpoint': [{'text': 'What is the most common mistake people make with PowerPoint slides?',
                 'explanation': 'Slides are read from across a room in a few seconds while you '
                                'talk. Put the short version on the slide and say the rest.',
                 'order': 0,
                 'choices': [{'text': 'Too few slides', 'is_correct': False, 'order': 0},
                             {'text': 'Treating a slide like a document page',
                              'is_correct': True,
                              'order': 1},
                             {'text': 'Using too few colours', 'is_correct': False, 'order': 2},
                             {'text': 'Not enough animation', 'is_correct': False, 'order': 3}]},
                {'text': 'What is the smallest font size you should use on a slide?',
                 'explanation': 'Below 24 point becomes unreadable from the back of a room. If '
                                'your text will not fit at 24, you have too much text.',
                 'order': 1,
                 'choices': [{'text': '12 point', 'is_correct': False, 'order': 0},
                             {'text': '18 point', 'is_correct': False, 'order': 1},
                             {'text': '24 point', 'is_correct': True, 'order': 2},
                             {'text': '10 point', 'is_correct': False, 'order': 3}]},
                {'text': 'Where should you put the detail you plan to say out loud?',
                 'explanation': 'The Notes pane is visible to you in Presenter View and never to '
                                'the audience.',
                 'order': 2,
                 'choices': [{'text': 'In small text at the bottom of the slide',
                              'is_correct': False,
                              'order': 0},
                             {'text': 'In the Notes pane', 'is_correct': True, 'order': 1},
                             {'text': 'On a handout only', 'is_correct': False, 'order': 2},
                             {'text': 'In the slide title', 'is_correct': False, 'order': 3}]},
                {'text': 'How should you resize an image so it does not distort?',
                 'explanation': 'Corner handles keep the proportions. Side handles stretch the '
                                'picture.',
                 'order': 3,
                 'choices': [{'text': 'Drag a side handle', 'is_correct': False, 'order': 0},
                             {'text': 'Drag a corner handle', 'is_correct': True, 'order': 1},
                             {'text': 'Change the slide size', 'is_correct': False, 'order': 2},
                             {'text': 'Use Crop', 'is_correct': False, 'order': 3}]},
                {'text': 'Which key blanks the screen to black during a presentation?',
                 'explanation': 'B blanks the screen so the room looks at you instead of the '
                                'slide. It is the most underused key in PowerPoint.',
                 'order': 4,
                 'choices': [{'text': 'N', 'is_correct': False, 'order': 0},
                             {'text': 'B', 'is_correct': True, 'order': 1},
                             {'text': 'Esc', 'is_correct': False, 'order': 2},
                             {'text': 'F5', 'is_correct': False, 'order': 3}]},
                {'text': 'What is the safest rule for colour on slides?',
                 'explanation': 'Projectors wash colours out badly. Anything low-contrast becomes '
                                'unreadable in the room even if it looks fine on your laptop.',
                 'order': 5,
                 'choices': [{'text': 'Use as many colours as possible',
                              'is_correct': False,
                              'order': 0},
                             {'text': 'Strong contrast: dark on light, or light on dark',
                              'is_correct': True,
                              'order': 1},
                             {'text': 'Match the company logo exactly',
                              'is_correct': False,
                              'order': 2},
                             {'text': 'Always use a photo background',
                              'is_correct': False,
                              'order': 3}]},
                {'text': 'When is animation genuinely useful?',
                 'explanation': 'Revealing points one at a time keeps the audience listening to '
                                'the current point instead of reading ahead.',
                 'order': 6,
                 'choices': [{'text': 'To make slides more exciting',
                              'is_correct': False,
                              'order': 0},
                             {'text': 'To reveal bullet points one at a time',
                              'is_correct': True,
                              'order': 1},
                             {'text': 'On every element', 'is_correct': False, 'order': 2},
                             {'text': 'For the title only', 'is_correct': False, 'order': 3}]},
                {'text': 'You need a title for a slide about sales rising. Which is better?',
                 'explanation': 'A title that states the finding tells the audience something. A '
                                'label just names the topic.',
                 'order': 7,
                 'choices': [{'text': 'Sales Update', 'is_correct': False, 'order': 0},
                             {'text': 'Quarterly sales rose 40%', 'is_correct': True, 'order': 1},
                             {'text': 'Sales', 'is_correct': False, 'order': 2},
                             {'text': 'Q4 Results', 'is_correct': False, 'order': 3}]},
                {'text': 'Why should you not pull images from a Google Search for a business '
                         'presentation?',
                 'explanation': 'Most search results are protected by copyright. Use Stock Images '
                                'inside PowerPoint, or Unsplash and Pexels.',
                 'order': 8,
                 'choices': [{'text': 'They are low quality', 'is_correct': False, 'order': 0},
                             {'text': 'They are usually copyrighted',
                              'is_correct': True,
                              'order': 1},
                             {'text': 'They load slowly', 'is_correct': False, 'order': 2},
                             {'text': 'They cannot be resized', 'is_correct': False, 'order': 3}]},
                {'text': 'What should you always carry as a backup when presenting?',
                 'explanation': 'A PDF opens on any machine. If PowerPoint is missing, the version '
                                'is wrong, or the file will not open, the PDF still works.',
                 'order': 9,
                 'choices': [{'text': 'A second laptop', 'is_correct': False, 'order': 0},
                             {'text': 'A PDF copy of the deck', 'is_correct': True, 'order': 1},
                             {'text': 'Printed handouts', 'is_correct': False, 'order': 2},
                             {'text': 'An extra projector', 'is_correct': False, 'order': 3}]}],
 'excel': [{'text': 'A column of numbers you typed appears on the LEFT side of the cells. What '
                    'does that tell you?',
            'explanation': 'Numbers align right, text aligns left. Left-aligned numbers are stored '
                           'as text, and SUM will return zero on them.',
            'order': 0,
            'choices': [{'text': 'They are formatted as currency', 'is_correct': False, 'order': 0},
                        {'text': 'Excel is treating them as text', 'is_correct': True, 'order': 1},
                        {'text': 'The column is too narrow', 'is_correct': False, 'order': 2},
                        {'text': 'They are negative', 'is_correct': False, 'order': 3}]},
           {'text': 'What must every formula begin with?',
            'explanation': 'The equals sign tells Excel to calculate instead of displaying what '
                           'you typed.',
            'order': 1,
            'choices': [{'text': 'A plus sign', 'is_correct': False, 'order': 0},
                        {'text': 'An equals sign', 'is_correct': True, 'order': 1},
                        {'text': 'A bracket', 'is_correct': False, 'order': 2},
                        {'text': 'The word SUM', 'is_correct': False, 'order': 3}]},
           {'text': 'What does the range B2:B10 mean?',
            'explanation': 'The colon means through. B2:B10 is all nine cells in that stretch.',
            'order': 2,
            'choices': [{'text': 'Cells B2 and B10 only', 'is_correct': False, 'order': 0},
                        {'text': 'Every cell from B2 down to B10', 'is_correct': True, 'order': 1},
                        {'text': 'B2 divided by B10', 'is_correct': False, 'order': 2},
                        {'text': 'Columns B through 10', 'is_correct': False, 'order': 3}]},
           {'text': 'You copy the formula =A1*E1 down a column and every result becomes zero. What '
                    'went wrong?',
            'explanation': 'Copying shifted E1 to E2, E3 and so on - empty cells. Writing $E$1 '
                           'pins it so every row keeps pointing at the rate.',
            'order': 3,
            'choices': [{'text': 'The numbers are text', 'is_correct': False, 'order': 0},
                        {'text': 'E1 needs to be locked as $E$1', 'is_correct': True, 'order': 1},
                        {'text': 'SUM should have been used', 'is_correct': False, 'order': 2},
                        {'text': 'The column is hidden', 'is_correct': False, 'order': 3}]},
           {'text': 'Which key cycles a reference through A1, $A$1, A$1 and $A1?',
            'explanation': 'Put the cursor on the reference in the formula bar and press F4 until '
                           'the form you want appears.',
            'order': 4,
            'choices': [{'text': 'F2', 'is_correct': False, 'order': 0},
                        {'text': 'F4', 'is_correct': True, 'order': 1},
                        {'text': 'F9', 'is_correct': False, 'order': 2},
                        {'text': 'Ctrl+D', 'is_correct': False, 'order': 3}]},
           {'text': 'What is the correct way to show PKR next to a number?',
            'explanation': 'Typing PKR turns the cell into text and breaks every formula that '
                           'touches it. Formatting leaves the number intact.',
            'order': 5,
            'choices': [{'text': 'Type PKR before the number', 'is_correct': False, 'order': 0},
                        {'text': 'Use the currency format from the Number group',
                         'is_correct': True,
                         'order': 1},
                        {'text': 'Add it in a separate column', 'is_correct': False, 'order': 2},
                        {'text': 'Use a text box', 'is_correct': False, 'order': 3}]},
           {'text': 'A cell suddenly shows hashes instead of a number. What does it mean?',
            'explanation': 'Nothing is wrong with the data. Double-click the border between column '
                           'headers to widen it.',
            'order': 6,
            'choices': [{'text': 'The formula is broken', 'is_correct': False, 'order': 0},
                        {'text': 'The column is too narrow', 'is_correct': True, 'order': 1},
                        {'text': 'The value is negative', 'is_correct': False, 'order': 2},
                        {'text': 'The cell is locked', 'is_correct': False, 'order': 3}]},
           {'text': 'Which formula counts how many sales came from Lahore, where cities are in '
                    'B2:B50?',
            'explanation': 'COUNTIF counts rows matching a condition. COUNT only counts numbers '
                           'and would give zero on text.',
            'order': 7,
            'choices': [{'text': '=COUNT(B2:B50)', 'is_correct': False, 'order': 0},
                        {'text': '=COUNTIF(B2:B50,"Lahore")', 'is_correct': True, 'order': 1},
                        {'text': '=SUMIF(B2:B50,"Lahore")', 'is_correct': False, 'order': 2},
                        {'text': '=COUNTA(B2:B50)', 'is_correct': False, 'order': 3}]},
           {'text': 'Why must VLOOKUP end with FALSE?',
            'explanation': 'Without FALSE, Excel does an approximate match and returns confidently '
                           'wrong answers on unsorted data.',
            'order': 8,
            'choices': [{'text': 'It makes it faster', 'is_correct': False, 'order': 0},
                        {'text': 'It forces an exact match instead of an approximate one',
                         'is_correct': True,
                         'order': 1},
                        {'text': 'It hides errors', 'is_correct': False, 'order': 2},
                        {'text': 'It is optional', 'is_correct': False, 'order': 3}]},
           {'text': 'What is the main limitation of VLOOKUP that XLOOKUP fixes?',
            'explanation': 'VLOOKUP requires the search value in the leftmost column. XLOOKUP '
                           'looks in any direction.',
            'order': 9,
            'choices': [{'text': 'It cannot handle text', 'is_correct': False, 'order': 0},
                        {'text': 'It only looks to the right of the search column',
                         'is_correct': True,
                         'order': 1},
                        {'text': 'It is limited to 100 rows', 'is_correct': False, 'order': 2},
                        {'text': 'It cannot be copied', 'is_correct': False, 'order': 3}]},
           {'text': 'Before sorting a range, what must you check?',
            'explanation': 'A blank row makes Excel think the data ends there. It then sorts only '
                           'part of it and silently scrambles the rest - very hard to spot '
                           'afterwards.',
            'order': 10,
            'choices': [{'text': 'That it is formatted as currency',
                         'is_correct': False,
                         'order': 0},
                        {'text': 'That there are no blank rows inside the data',
                         'is_correct': True,
                         'order': 1},
                        {'text': 'That it has fewer than 100 rows',
                         'is_correct': False,
                         'order': 2},
                        {'text': 'That a chart exists', 'is_correct': False, 'order': 3}]},
           {'text': "Your PivotTable is showing last week's numbers even though the data has "
                    'changed. Why?',
            'explanation': 'Right-click the pivot and choose Refresh. Building it on a Table '
                           '(Ctrl+T) also picks up new rows on refresh.',
            'order': 11,
            'choices': [{'text': 'The data is corrupt', 'is_correct': False, 'order': 0},
                        {'text': 'Pivots do not refresh automatically',
                         'is_correct': True,
                         'order': 1},
                        {'text': 'The filter is on', 'is_correct': False, 'order': 2},
                        {'text': 'Excel needs restarting', 'is_correct': False, 'order': 3}]},
           {'text': 'What is the best defence against a city being entered as Lahore, lahore and '
                    'Lahroe?',
            'explanation': 'A dropdown stops the bad values getting in at all. COUNTIF would treat '
                           'those three spellings as different cities.',
            'order': 12,
            'choices': [{'text': 'Conditional formatting', 'is_correct': False, 'order': 0},
                        {'text': 'A Data Validation dropdown list', 'is_correct': True, 'order': 1},
                        {'text': 'Sorting the column', 'is_correct': False, 'order': 2},
                        {'text': 'Using COUNTIF', 'is_correct': False, 'order': 3}]},
           {'text': 'You have ten categories to compare. Which chart type should you avoid?',
            'explanation': 'People cannot compare angles accurately. Above about five slices, a '
                           'bar chart communicates far better.',
            'order': 13,
            'choices': [{'text': 'Bar chart', 'is_correct': False, 'order': 0},
                        {'text': 'Column chart', 'is_correct': False, 'order': 1},
                        {'text': 'Pie chart', 'is_correct': True, 'order': 2},
                        {'text': 'Line chart', 'is_correct': False, 'order': 3}]}],
 'vba': [{'text': 'You save a workbook containing macros as a normal .xlsx file. What happens?',
          'explanation': 'Only .xlsm files can store macros. Excel warns you, but the warning is '
                         'easy to click past and the code is gone once the file closes.',
          'order': 0,
          'choices': [{'text': 'Nothing, it works fine', 'is_correct': False, 'order': 0},
                      {'text': 'The macros are stripped out', 'is_correct': True, 'order': 1},
                      {'text': 'Excel refuses to save', 'is_correct': False, 'order': 2},
                      {'text': 'The file becomes read-only', 'is_correct': False, 'order': 3}]},
         {'text': 'Which shortcut opens the VBA editor?',
          'explanation': 'Alt+F11 opens the editor. Alt+F8 opens the list of macros to run.',
          'order': 1,
          'choices': [{'text': 'Alt+F8', 'is_correct': False, 'order': 0},
                      {'text': 'Alt+F11', 'is_correct': True, 'order': 1},
                      {'text': 'Ctrl+F11', 'is_correct': False, 'order': 2},
                      {'text': 'F5', 'is_correct': False, 'order': 3}]},
         {'text': 'What does this line do?  lastRow = Cells(Rows.Count, 1).End(xlUp).Row',
          'explanation': 'It jumps to the bottom of column A, then travels up to the last filled '
                         'cell, and takes its row number. This makes a macro work on 5 rows or '
                         '50,000 without changes.',
          'order': 2,
          'choices': [{'text': 'Counts every row in the sheet', 'is_correct': False, 'order': 0},
                      {'text': 'Finds the last row that has data in column A',
                       'is_correct': True,
                       'order': 1},
                      {'text': 'Deletes empty rows', 'is_correct': False, 'order': 2},
                      {'text': 'Selects column A', 'is_correct': False, 'order': 3}]},
         {'text': 'Why must a loop that deletes rows count backwards with Step -1?',
          'explanation': 'Delete row 5 and the old row 6 becomes row 5, but the loop has already '
                         'moved to 6 - so that row is never checked. Backwards is the only '
                         'reliable way.',
          'order': 3,
          'choices': [{'text': 'It runs faster', 'is_correct': False, 'order': 0},
                      {'text': 'Deleting a row shifts the ones below up, so a forward loop skips '
                               'rows',
                       'is_correct': True,
                       'order': 1},
                      {'text': 'VBA requires it', 'is_correct': False, 'order': 2},
                      {'text': 'It uses less memory', 'is_correct': False, 'order': 3}]},
         {'text': 'What is wrong with leaving On Error Resume Next in a macro?',
          'explanation': 'The macro appears to work while producing wrong results. Handle the '
                         'errors you expect, and let the rest surface.',
          'order': 4,
          'choices': [{'text': 'It slows the macro down', 'is_correct': False, 'order': 0},
                      {'text': 'It hides every error, including ones that matter',
                       'is_correct': True,
                       'order': 1},
                      {'text': 'It is not valid VBA', 'is_correct': False, 'order': 2},
                      {'text': 'It only works once', 'is_correct': False, 'order': 3}]},
         {'text': "Can a macro's changes be undone with Ctrl+Z?",
          'explanation': 'Macros clear the undo stack. Always test on a copy, and keep a backup '
                         'when the macro deletes anything.',
          'order': 5,
          'choices': [{'text': 'Yes, always', 'is_correct': False, 'order': 0},
                      {'text': 'No - anything a macro does is permanent',
                       'is_correct': True,
                       'order': 1},
                      {'text': 'Only for formatting changes', 'is_correct': False, 'order': 2},
                      {'text': 'Only within 30 seconds', 'is_correct': False, 'order': 3}]},
         {'text': 'Why set Application.ScreenUpdating = False at the start of a long macro?',
          'explanation': 'Always set it back to True at the end. If the macro errors out while it '
                         'is off, Excel appears frozen.',
          'order': 6,
          'choices': [{'text': 'It hides the macro from users', 'is_correct': False, 'order': 0},
                      {'text': 'Excel stops repainting after every change, so it runs much faster',
                       'is_correct': True,
                       'order': 1},
                      {'text': 'It prevents errors', 'is_correct': False, 'order': 2},
                      {'text': 'It saves the file', 'is_correct': False, 'order': 3}]},
         {'text': 'Where can VBA macros run?',
          'explanation': 'If the workbook must work in a browser, formulas or Power Query are the '
                         'right tool instead.',
          'order': 7,
          'choices': [{'text': 'Everywhere Excel runs', 'is_correct': False, 'order': 0},
                      {'text': 'Windows desktop Excel - not Excel on the web, and only partly on '
                               'Mac',
                       'is_correct': True,
                       'order': 1},
                      {'text': 'Only in Excel 365', 'is_correct': False, 'order': 2},
                      {'text': 'Only on Mac', 'is_correct': False, 'order': 3}]},
         {'text': 'A workbook arrives by email from an unknown sender and asks you to enable '
                  'macros. What should you do?',
          'explanation': 'A macro can do anything your user account can do, including deleting '
                         'files. Macro-borne malware is still common.',
          'order': 8,
          'choices': [{'text': 'Enable them - Excel files are safe',
                       'is_correct': False,
                       'order': 0},
                      {'text': 'Do not enable them', 'is_correct': True, 'order': 1},
                      {'text': 'Enable them but save first', 'is_correct': False, 'order': 2},
                      {'text': 'Enable them in a new window', 'is_correct': False, 'order': 3}]},
         {'text': 'Which is the better way to write to a cell?',
          'explanation': 'Writing directly is faster and does not disturb whatever the user had '
                         'selected. The macro recorder teaches the .Select habit, but you should '
                         'drop it.',
          'order': 9,
          'choices': [{'text': 'Range("A1").Select then Selection.Value = 5',
                       'is_correct': False,
                       'order': 0},
                      {'text': 'Range("A1").Value = 5', 'is_correct': True, 'order': 1},
                      {'text': 'Both are identical', 'is_correct': False, 'order': 2},
                      {'text': 'Cells.Select first', 'is_correct': False, 'order': 3}]}],
 'alquran': [{'text': "عربی گرامر میں 'اسم' کسے کہتے ہیں؟",
              'explanation': 'اسم نام ظاہر کرتا ہے — جیسے كِتَاب، يَوْم۔ کام ظاہر کرنے والا لفظ '
                             'فعل کہلاتا ہے۔',
              'order': 0,
              'choices': [{'text': 'جس سے کام کرنا ظاہر ہو', 'is_correct': False, 'order': 0},
                          {'text': 'جس سے کسی چیز، شخص یا معنی کا نام ظاہر ہو',
                           'is_correct': True,
                           'order': 1},
                          {'text': 'جو دو الفاظ کو جوڑے', 'is_correct': False, 'order': 2},
                          {'text': 'جو سوال کے لیے آئے', 'is_correct': False, 'order': 3}]},
             {'text': "عربی گرامر میں 'فعل' کسے کہتے ہیں؟",
              'explanation': 'فعل کام یا ہونا بتاتا ہے۔ اسم نام بتاتا ہے۔ یہی پہلا فرق ہے جو سبق ۱ '
                             'میں پڑھایا گیا۔',
              'order': 1,
              'choices': [{'text': 'جو کسی چیز کا نام ہو', 'is_correct': False, 'order': 0},
                          {'text': 'جس سے کام کرنا یا ہونا ظاہر ہو',
                           'is_correct': True,
                           'order': 1},
                          {'text': 'جو صرف قرآن میں آئے', 'is_correct': False, 'order': 2},
                          {'text': 'جو ہمیشہ آخر میں آئے', 'is_correct': False, 'order': 3}]},
             {'text': "'كِتَاب' کا معنی کیا ہے؟",
              'explanation': 'كِتَاب یعنی کتاب۔ یہ سبق ۱ کے پانچ الفاظ میں شامل ہے۔',
              'order': 2,
              'choices': [{'text': 'دن', 'is_correct': False, 'order': 0},
                          {'text': 'کتاب', 'is_correct': True, 'order': 1},
                          {'text': 'رب', 'is_correct': False, 'order': 2},
                          {'text': 'آسمان', 'is_correct': False, 'order': 3}]},
             {'text': "'يَوْم' کا معنی کیا ہے؟",
              'explanation': 'يَوْم یعنی دن۔ یہ بھی سبق ۱ کے الفاظ میں ہے۔',
              'order': 3,
              'choices': [{'text': 'رات', 'is_correct': False, 'order': 0},
                          {'text': 'دن', 'is_correct': True, 'order': 1},
                          {'text': 'سال', 'is_correct': False, 'order': 2},
                          {'text': 'مہینہ', 'is_correct': False, 'order': 3}]},
             {'text': "'رَبّ' کا معنی کیا ہے؟",
              'explanation': 'رَبّ یعنی رب یا پروردگار۔',
              'order': 4,
              'choices': [{'text': 'بندہ', 'is_correct': False, 'order': 0},
                          {'text': 'رب / پروردگار', 'is_correct': True, 'order': 1},
                          {'text': 'راستہ', 'is_correct': False, 'order': 2},
                          {'text': 'گھر', 'is_correct': False, 'order': 3}]},
             {'text': "'آيَة' کا معنی کیا ہے؟",
              'explanation': 'آيَة کے دو معنی سبق میں دیے گئے: آیت اور نشانی۔',
              'order': 5,
              'choices': [{'text': 'آیت / نشانی', 'is_correct': True, 'order': 0},
                          {'text': 'آواز', 'is_correct': False, 'order': 1},
                          {'text': 'انسان', 'is_correct': False, 'order': 2},
                          {'text': 'زمین', 'is_correct': False, 'order': 3}]},
             {'text': 'ان میں سے کون سا لفظ اسم ہے؟',
              'explanation': 'كِتَاب ایک نام ہے، اس لیے اسم ہے۔ باقی تینوں کام ظاہر کرتے ہیں۔',
              'order': 6,
              'choices': [{'text': 'كَتَبَ', 'is_correct': False, 'order': 0},
                          {'text': 'كِتَاب', 'is_correct': True, 'order': 1},
                          {'text': 'يَكْتُبُ', 'is_correct': False, 'order': 2},
                          {'text': 'اُكْتُبْ', 'is_correct': False, 'order': 3}]},
             {'text': 'یہ کورس کتنے دن کا ہے؟',
              'explanation': 'تیس مختصر روزانہ اسباق، ہر سبق تقریباً تیس منٹ کا۔',
              'order': 7,
              'choices': [{'text': 'سات دن', 'is_correct': False, 'order': 0},
                          {'text': 'پندرہ دن', 'is_correct': False, 'order': 1},
                          {'text': 'تیس دن', 'is_correct': True, 'order': 2},
                          {'text': 'ساٹھ دن', 'is_correct': False, 'order': 3}]},
             {'text': 'ہر سبق میں تقریباً کتنا وقت لگتا ہے؟',
              'explanation': 'ہر سبق کے شروع میں لکھا ہے: کل وقت 30 منٹ۔',
              'order': 8,
              'choices': [{'text': 'دس منٹ', 'is_correct': False, 'order': 0},
                          {'text': 'تیس منٹ', 'is_correct': True, 'order': 1},
                          {'text': 'دو گھنٹے', 'is_correct': False, 'order': 2},
                          {'text': 'پورا دن', 'is_correct': False, 'order': 3}]},
             {'text': 'اس کورس کا بنیادی مقصد کیا ہے؟',
              'explanation': 'یہ کورس زبان سکھاتا ہے: الفاظ، اسم و فعل کا فرق، اور چھوٹی عبارتیں '
                             'لفظ بہ لفظ پڑھنا۔',
              'order': 9,
              'choices': [{'text': 'قرآن حفظ کرنا', 'is_correct': False, 'order': 0},
                          {'text': 'قرآنی عربی کے الفاظ اور بنیادی قواعد سمجھنا',
                           'is_correct': True,
                           'order': 1},
                          {'text': 'تجوید سیکھنا', 'is_correct': False, 'order': 2},
                          {'text': 'فقہی مسائل جاننا', 'is_correct': False, 'order': 3}]},
             {'text': "سبق میں 'لفظ بہ لفظ' سے کیا مراد ہے؟",
              'explanation': 'لفظ بہ لفظ یعنی ہر لفظ کا معنی الگ سے دیکھنا — اسی سے پوری عبارت '
                             'سمجھ آتی ہے۔',
              'order': 10,
              'choices': [{'text': 'پوری عبارت کا خلاصہ', 'is_correct': False, 'order': 0},
                          {'text': 'ہر لفظ کا الگ الگ معنی سمجھنا', 'is_correct': True, 'order': 1},
                          {'text': 'عبارت کو یاد کرنا', 'is_correct': False, 'order': 2},
                          {'text': 'عبارت کو خوش خط لکھنا', 'is_correct': False, 'order': 3}]},
             {'text': 'روزانہ سیکھنے کا بہترین طریقہ کورس میں کیا بتایا گیا؟',
              'explanation': 'کورس روزانہ کے تیس منٹ پر بنایا گیا ہے — تھوڑا مگر باقاعدہ۔',
              'order': 11,
              'choices': [{'text': 'مہینے میں ایک بار سب کچھ پڑھنا',
                           'is_correct': False,
                           'order': 0},
                          {'text': 'روزانہ ایک مختصر سبق اور مشق', 'is_correct': True, 'order': 1},
                          {'text': 'صرف الفاظ کی فہرست یاد کرنا', 'is_correct': False, 'order': 2},
                          {'text': 'صرف قواعد پڑھنا', 'is_correct': False, 'order': 3}]}]}

class Command(BaseCommand):
    help = "Create or update the Academy courses, lessons and quiz bank. Safe to re-run."

    def add_arguments(self, parser):
        parser.add_argument(
            "--replace-quiz", action="store_true",
            help="Delete and rebuild the question bank. Past attempts keep their "
                 "recorded score but lose the link to individual questions.",
        )

    @transaction.atomic
    def handle(self, *args, **opts):
        for cdata in COURSES:
            course, created = Course.objects.update_or_create(
                slug=cdata["slug"],
                defaults={
                    "title": cdata["title"],
                    "icon": cdata["icon"],
                    "accent": cdata["accent"],
                    "blurb": cdata["blurb"],
                    "order": cdata["order"],
                    "is_active": True,
                },
            )
            self.stdout.write(("created " if created else "updated ") + course.slug)

            seen = []
            for ldata in cdata["lessons"]:
                Lesson.objects.update_or_create(
                    course=course, key=ldata["key"],
                    defaults={"title": ldata["title"],
                              "minutes": ldata["minutes"],
                              "order": ldata["order"]},
                )
                seen.append(ldata["key"])

            # Lessons removed from the content file are dropped, along with any
            # progress rows pointing at them.
            stale = Lesson.objects.filter(course=course).exclude(key__in=seen)
            if stale.exists():
                self.stdout.write(self.style.WARNING(
                    "  removing %d lesson(s) no longer in the content: %s"
                    % (stale.count(), ", ".join(stale.values_list("key", flat=True)))
                ))
                stale.delete()

            self.stdout.write("  lessons: %d" % len(seen))

            qdata = QUIZ.get(cdata["slug"], [])
            existing = Question.objects.filter(course=course).count()

            if existing and not opts["replace_quiz"]:
                self.stdout.write("  quiz: %d questions already present, left alone "
                                  "(use --replace-quiz to rebuild)" % existing)
                continue

            Question.objects.filter(course=course).delete()
            for q in qdata:
                question = Question.objects.create(
                    course=course, text=q["text"],
                    explanation=q["explanation"], order=q["order"],
                )
                for ch in q["choices"]:
                    Choice.objects.create(
                        question=question, text=ch["text"],
                        is_correct=ch["is_correct"], order=ch["order"],
                    )
            self.stdout.write("  quiz: %d questions written" % len(qdata))

        self.stdout.write(self.style.SUCCESS("Done."))
