# Generated by Django 5.2.17 on 2026-10-01 07:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('tagline', models.CharField(blank=True, default='', max_length=160)),
                ('about', models.TextField(blank=True, default='', max_length=4000)),
                ('industry', models.CharField(blank=True, default='', max_length=80)),
                ('size', models.CharField(blank=True, default='', max_length=20)),
                ('founded', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('country', models.CharField(blank=True, default='PK', max_length=2)),
                ('address', models.CharField(blank=True, default='', max_length=240)),
                ('website', models.URLField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=24)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=24)),
                ('logo', models.CharField(blank=True, default='', max_length=200)),
                ('cover', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Waiting for review'), ('approved', 'Verified'), ('rejected', 'Not approved')], db_index=True, default='draft', max_length=10)),
                ('review_note', models.CharField(blank=True, default='', max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, default='', max_length=120)),
                ('domain_token', models.CharField(blank=True, default='', max_length=40)),
                ('domain_verified_at', models.DateTimeField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('registration', 'Registration certificate'), ('cheque', 'Cheque copy'), ('ntn', 'NTN / tax certificate'), ('other', 'Other proof')], max_length=14)),
                ('path', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='companies.company')),
            ],
        ),
    ]
