# Generated by Django 5.2.17 on 2026-10-01 07:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonKyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Waiting for review'), ('approved', 'Blue tick given'), ('rejected', 'Not approved')], db_index=True, default='draft', max_length=10)),
                ('review_note', models.CharField(blank=True, default='', max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cnic_front', 'CNIC front'), ('cnic_back', 'CNIC back'), ('passport', 'Passport'), ('address', 'Address proof'), ('other', 'Other proof')], max_length=12)),
                ('path', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='companies.personkyc')),
            ],
        ),
    ]
