# Generated by Django 5.2.17 on 2026-10-04 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=40)),
                ('company', models.CharField(max_length=10)),
                ('ref', models.CharField(max_length=24)),
                ('due_day', models.PositiveSmallIntegerField(default=15)),
                ('remind', models.BooleanField(default=True)),
                ('last_reminded', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
