# Generated by Django 5.2.17 on 2026-10-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biller',
            name='country',
            field=models.CharField(default='PK', max_length=2),
        ),
        migrations.AddField(
            model_name='biller',
            name='label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='biller',
            name='link',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='biller',
            name='company',
            field=models.CharField(max_length=20),
        ),
    ]
