# Generated by Django 5.2.17 on 2026-10-09 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('size', models.PositiveSmallIntegerField(default=2)),
                ('players', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='wait', max_length=8)),
                ('state', models.JSONField(blank=True, null=True)),
                ('shot', models.JSONField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrom_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
