# Generated by Django 5.2.17 on 2026-10-01 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.CharField(blank=True, default='', max_length=40)),
                ('place', models.CharField(blank=True, default='', max_length=120)),
                ('tagged', models.JSONField(blank=True, default=list)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xmeta', to='feed.post')),
            ],
        ),
    ]
