# Generated by Django 5.2.17 on 2026-10-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmeta',
            name='bg',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='postmeta',
            name='fg',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
