# Generated by Django 5.2.17 on 2026-10-01 13:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0009_chatmessage_voice_chatmessage_voice_secs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed', models.BooleanField(db_index=True, default=True)),
                ('listed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='notifications.chatgroup')),
            ],
        ),
    ]
