# Generated by Django 5.2.17 on 2026-09-19 23:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(db_index=True, help_text='Course id, e.g. python', max_length=32)),
                ('title', models.CharField(max_length=140)),
                ('note', models.TextField(blank=True, default='', help_text='What the video covers')),
                ('source', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo')], default='youtube', max_length=10)),
                ('video_id', models.CharField(max_length=32)),
                ('state', models.CharField(choices=[('pending', 'Waiting to be checked'), ('live', 'Published'), ('rejected', 'Turned down')], db_index=True, default='pending', max_length=10)),
                ('decision_note', models.CharField(blank=True, default='', max_length=300)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('up', models.PositiveIntegerField(default=0)),
                ('down', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_posts', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_decided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Helpful'), (-1, 'Not helpful')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='academy.videopost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='videopost',
            index=models.Index(fields=['course', 'state'], name='academy_vid_course_ba6e07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videovote',
            unique_together={('post', 'user')},
        ),
    ]
