# Generated by Django 5.2.17 on 2026-09-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_videopost_videovote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='review_ok',
            field=models.BooleanField(default=True),
        ),
    ]
