# Generated by Django 5.2.17 on 2026-10-04 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('website', models.URLField(blank=True, default='', max_length=300)),
                ('helpline', models.CharField(blank=True, default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(db_index=True, max_length=40)),
                ('to_city', models.CharField(db_index=True, max_length=40)),
                ('times', models.JSONField(default=list)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('fare', models.PositiveIntegerField(default=0)),
                ('service', models.CharField(blank=True, default='', max_length=40)),
                ('checked', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='bus.company')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bus.route')),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('map_url', models.URLField(blank=True, default='', max_length=400)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='bus.company')),
            ],
        ),
    ]
