# Generated by Django 5.2.17 on 2026-08-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
