# Generated by Django 5.2.17 on 2026-09-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guest_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='host_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
