# Generated by Django 5.2.17 on 2026-09-24 16:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('tv', 'Drama / series'), ('movie', 'Movie')], default='tv', max_length=5)),
                ('tmdb_id', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(help_text='The drama or movie, for your own reference', max_length=200)),
                ('label', models.CharField(default='Watch on the official channel', help_text="e.g. 'All episodes on HUM TV'", max_length=80)),
                ('url', models.URLField(max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TitleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('tv', 'Drama / series'), ('movie', 'Movie')], max_length=5)),
                ('tmdb_id', models.PositiveIntegerField(db_index=True)),
                ('stars', models.PositiveSmallIntegerField()),
                ('text', models.TextField(blank=True, default='', max_length=1000)),
                ('hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'kind', 'tmdb_id')},
            },
        ),
        migrations.CreateModel(
            name='WatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('tv', 'Drama / series'), ('movie', 'Movie')], max_length=5)),
                ('tmdb_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('poster', models.CharField(blank=True, default='', max_length=200)),
                ('year', models.CharField(blank=True, default='', max_length=4)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'kind', 'tmdb_id')},
            },
        ),
    ]
