# Generated by Django 5.2.17 on 2026-10-02 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAyah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('ref', models.CharField(max_length=10)),
                ('surah', models.CharField(default='', max_length=80)),
                ('arabic', models.TextField()),
                ('urdu', models.TextField(blank=True, default='')),
                ('english', models.TextField(blank=True, default='')),
                ('hijri', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(default='main', max_length=20)),
                ('serves', models.PositiveSmallIntegerField(default=4)),
                ('minutes', models.PositiveSmallIntegerField(default=30)),
                ('intro', models.CharField(blank=True, default='', max_length=300)),
                ('ingredients', models.JSONField(default=list)),
                ('steps', models.JSONField(default=list)),
                ('photo', models.CharField(blank=True, default='', max_length=200)),
                ('approved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
