# Generated by Django 5.2.17 on 2026-08-11 04:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(db_index=True, default='Pakistan', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('allow_call', models.BooleanField(default=True)),
                ('allow_whatsapp', models.BooleanField(default=True)),
                ('allow_sms', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True, help_text="Donor's own switch. Turning it off hides them from searches.")),
                ('last_donation', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Set by an admin after checking ID.')),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Waiting'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('requester_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asks', to='bloodbank.donor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('handled', models.BooleanField(default=False)),
                ('ask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodbank.ask')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, default='', max_length=120)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('units', models.PositiveSmallIntegerField(default=1)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('hospital', models.CharField(max_length=200)),
                ('urgency', models.CharField(choices=[('normal', 'Within a few days'), ('urgent', 'Today'), ('critical', 'Right now')], default='urgent', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('contact_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='open', max_length=10)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ask',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asks', to='bloodbank.request'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['city', 'blood_group', 'is_available'], name='bloodbank_d_city_6c8bd5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ask',
            unique_together={('request', 'donor')},
        ),
    ]
