# Generated by Django 5.2.17 on 2026-09-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='a_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='a_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='b_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='b_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='disappear_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
