# Generated by Django 5.2.17 on 2026-09-25 20:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_chatmessage_system_chatthread_a_cleared_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('link', models.CharField(blank=True, default='', max_length=200)),
                ('audience', models.CharField(choices=[('all', 'All members'), ('verified', 'Members with a verified email')], default='all', max_length=10)),
                ('push', models.BooleanField(default=True)),
                ('recipients', models.PositiveIntegerField(default=0)),
                ('devices', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
