# Generated by Django 5.2.17 on 2026-09-26 16:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_chatgroup_groupmessage_groupprivacy_groupinvite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='bot_mod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='msg_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='muted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='warnings',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GroupBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(default='XpertBot', max_length=30)),
                ('greeting', models.CharField(default='Welcome to {group}, {name}! 👋 Type !help to see what I can do, and !rules for the group rules.', max_length=300)),
                ('rules', models.TextField(blank=True, default='1. Be kind and respectful.\n2. No spam or advertising.\n3. No abuse or bad language.', max_length=1500)),
                ('bad_words', models.TextField(blank=True, default='', max_length=3000)),
                ('warn_limit', models.PositiveSmallIntegerField(default=3)),
                ('mute_minutes', models.PositiveSmallIntegerField(default=30)),
                ('flood_count', models.PositiveSmallIntegerField(default=6)),
                ('flood_seconds', models.PositiveSmallIntegerField(default=10)),
                ('links_admins_only', models.BooleanField(default=False)),
                ('pin_admins_only', models.BooleanField(default=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot', to='notifications.chatgroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupBotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('target', models.CharField(blank=True, default='', max_length=120)),
                ('by', models.CharField(blank=True, default='', max_length=120)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_log', to='notifications.chatgroup')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GroupBotTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('every_hours', models.PositiveSmallIntegerField(default=0)),
                ('daily_at', models.TimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(db_index=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_timers', to='notifications.chatgroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='notifications.chatgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'user')},
            },
        ),
    ]
