# Generated by Django 5.2.17 on 2026-09-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_chatmessage_pinned_chatmessage_pinned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='voice',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='voice_secs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='voice',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='voice_secs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
