# Generated by Django 5.2.17 on 2026-10-03 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KidsChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('category', models.CharField(choices=[('islamic', 'Islamic'), ('learning', 'Learning'), ('rhymes', 'Rhymes'), ('stories', 'Stories'), ('cartoons', 'Cartoons')], default='cartoons', max_length=10)),
                ('age', models.CharField(choices=[('2-5', '2 to 5'), ('6-10', '6 to 10'), ('all', 'All ages')], default='all', max_length=5)),
                ('active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KidsVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('published', models.DateTimeField(db_index=True)),
                ('hidden', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='kids.kidschannel')),
            ],
        ),
    ]
